// Bundle src/main.js (+three) into a single self-contained HTML that opens by double-click.
import { build } from 'esbuild';
import { readFileSync, writeFileSync, mkdirSync, copyFileSync, existsSync } from 'fs';
import { buildBrainGraph } from './graph-build.mjs';
await buildBrainGraph(); // V3.6: bake the vault's wiki-link graph into src/braingraph.js

// TYLER-TOWER: bundle citizens into the app BEFORE esbuild (works file:// and http, zero fetches)
try {
  if (existsSync('brain/agency-personas/citizens.json')) {
    const data = JSON.parse(readFileSync('brain/agency-personas/citizens.json', 'utf8'));
    // Phase 9 load budget: the roster UI reads at most 110 chars of description and the
    // offline demo replies are read aloud at most ~220 chars. Trim once here so the bundle
    // does not carry megabytes the client never shows. 282 citizens × full text was 469 KB.
    const trim = (s, n) => (typeof s === 'string' && s.length > n ? s.slice(0, n).replace(/\s+\S*$/, '') : s);
    const citizens = data.citizens.map(c => ({
      ...c,
      description: trim(c.description, 160),
      greeting: trim(c.greeting, 220),
      demo: Array.isArray(c.demo)
        ? c.demo.slice(0, 4).map(r => ({ k: Array.isArray(r.k) ? r.k.slice(0, 4) : r.k, r: trim(r.r, 220) }))
        : c.demo,
    }));
    writeFileSync('src/bench-data.js', `// GENERATED by build.mjs — do not edit. ${data.total} citizens.\nexport const CITIZENS = ${JSON.stringify(citizens)};\nexport const CITIZEN_GENERATED = ${JSON.stringify(data.generated)};\n`);
    console.log(`baked src/bench-data.js (${data.total} citizens, trimmed)`);
  }
} catch (e) { console.warn('bench-data:', e.message); }

const res = await build({
  entryPoints: ['src/main.js'],
  bundle: true,
  format: 'iife',
  minify: true,
  write: false,
  target: 'es2020',
});
const js = res.outputFiles[0].text;
const shell = readFileSync('src/shell.html', 'utf8');
const html = shell.replace('<!--APP-->', () => `<script>${js}</script>`);
mkdirSync('dist', { recursive: true });
writeFileSync('dist/command-centre-v2.html', html);
writeFileSync('dist/index.html', html);

// TYLER-TOWER: bake bench + skill indexes for the 3D bench ring (non-breaking statics)
try { if (existsSync('brain/agency-personas/BENCHES.json')) copyFileSync('brain/agency-personas/BENCHES.json', 'dist/benches.json'); } catch {}
try { if (existsSync('brain/agency-personas/index.json')) copyFileSync('brain/agency-personas/index.json', 'dist/aa-index.json'); } catch {}
try { if (existsSync('brain/agency-personas/citizens.json')) copyFileSync('brain/agency-personas/citizens.json', 'dist/citizens.json'); } catch {}

// dev variant with external script for faster iteration
mkdirSync('dist', { recursive: true });
writeFileSync('dist/app.js', js);
writeFileSync('dist/dev.html', shell.replace('<!--APP-->', '<script src="app.js"></script>'));
console.log(`🏰 built Tyler Tower production bundle: dist/command-centre-v2.html & dist/index.html (${(html.length / 1024).toFixed(0)} KB)`);
